### ISSUE TITLE
无法安装依赖

### ISSUE THREAD

**Issue by MenchW** [bit-ocean-studio/dolphin-admin-react#112]
## 执行操作
pnpm i

## 期望预期
依赖安装完毕 正常运行项目

## 实际效果
项目中安装了未发布依赖或未在工作区的依赖
报错:   ERR_PNPM_NO_VERSIONS  No versions available for @dolphin-admin/auto-import. The package may be unpublished.
 ERR_PNPM_NO_VERSIONS  No versions available for @dolphin-admin/auto-import. The package may be unpublished.

 ERR_PNPM_NO_VERSIONS  No versions available for @brucesong/eslint-config-react. The package may be unpublished.
 ERR_PNPM_NO_VERSIONS  No versions available for @dolphin-admin/bootstrap-animation. The package may be unpublished.
Progress: resolved 20, reused 0, downloaded 0, added 0

**Comment by recallwei** [comment]
`@dolphin-admin` is deprecated, try to use `@bit-ocean/*`.

```
pnpm add @bit-ocean/auto-import  @bit-ocean/eslint-config
```

**Comment by MenchW** [comment]
What should be a replacement for `@brucesong/eslint-config-react`?

**Comment by MenchW** [comment]
after installation, there are still a large number of usage issues. It is recommended to have a stable version

**Comment by recallwei** [comment]
> after installation, there are still a large number of usage issues. It is recommended to have a stable version

The dolphin admin will be rewritten in the future, and it is currently abandoned. You can add my WeChat to contact me (Recall4056).
